#!/bin/ksh

targetBin=$1
targetLibPerl=$2
targetTest=$3
checkoutFirst=$4

if [ "$3" = "" ]; then
  echo "usage: install targetBin targetLibPerl targetTest -checkoutfirst";
  exit 1;
fi

mkdir -p $targetBin
mkdir -p $targetLibPerl
mkdir -p $targetTest

oldpwd=$PWD
cd $COMPONENTS_HOME

if [ "$checkoutFirst" = "-checkoutfirst" ]; then
  cvs co \
  DistribJobTasks \
  DistribJob/install \
  perl/lib/Common \
  perl/lib/Blast \
  perl/lib/FastaIndex.pm \
  perl/lib/FastaFile.pm \
  perl/lib/TO.pm 
fi

# bin
/bin/cp DistribJobTasks/bin/!(CVS)                  $targetBin

# perl lib
/bin/rm -rf $targetLibPerl/DistribJobTasks
/bin/cp -r DistribJobTasks/lib/perl/DistribJobTasks $targetLibPerl
/bin/cp -r perl/lib/Common                          $targetLibPerl
/bin/cp -r perl/lib/Blast                           $targetLibPerl
/bin/cp -r perl/lib/FastaIndex.pm                   $targetLibPerl
/bin/cp -r perl/lib/FastaFile.pm                    $targetLibPerl
/bin/cp -r perl/lib/TO.pm                           $targetLibPerl

# test
/bin/rm -rf $targetTest/DistribJobTasks
/bin/cp -r DistribJobTasks/test/                    $targetTest/DistribJobTasks

chmod +x $targetBin/*

cd $oldpwd
$COMPONENTS_HOME/DistribJob/install $*
